apiVersion: batch/v1
kind: Job
metadata:
  name: http-reader
spec:
  backoffLimit: 1
  parallelism: 5
  template:
    metadata:
      labels:
        job-name: http-reader
        metrics: enabled
    spec:
      serviceAccount: http-reader
      containers:
        - name: main
          image: http-reader:latest
          command: ["java"]
          args:
           - "-jar"
           - "/deployments/enmasse-scaletest-http-reader-1.0.0-SNAPSHOT.jar"
          env:
            - name: IOT_PROJECT
              value: iot
            - name: MAX_DEVICES_CREATED
              value: "2000"
            - name: DEVICES_TO_READ
              value: "-1"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: REGISTRY_URL
              value: http://iot-device-registry-debug-endpoint.enmasse-infra.svc
            - name: INSECURE_TLS
              value: "true"
            - name: VERIFY_PASSWORDS
              value: "true"
          ports:
            - name: metrics
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: "500m"
            limits:
              cpu: "500m"
              memory: 256Mi
      restartPolicy: Never
