apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-device-registry-debug-endpoint-sidecar-nginx-config
  namespace: enmasse-infra
  
data:
  nginx.conf: |
    
    user  nginx;
    worker_processes  1;

    error_log  /dev/stdout info;
    pid        /tmp/nginx.pid;


    events {
        worker_connections  1024;
    }

    stream { 
        server {
            listen     8082;
            proxy_pass localhost:44120;
        }
    }

